[package]
name = "keen-retry"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]


[dependencies]
futures = "0.3"
tokio = { version = "1", features = ["full"] }


[dev-dependencies]
thiserror = "1.0"
